### ISSUE TITLE
Strip dots from target hostname in `now dns add`

### ISSUE THREAD

**Issue by leo** [zeit/now-cli#918]
This error could be avoided by stripping the dot from the end of the target hostname:

```
Ash:$ now dns add ashconnell.com @ MX alt4.aspmx.l.google.com. 10
> Error! Unexpected error. Please try again later. (Invalid `value` parameter (not a valid FQDN))
```

**Comment by matheuss** [comment]
👎 We should fix the API instead – while `google.com` is a domain name, `google.com.` is the fully qualified domain name (FQDN). cc @OlliV

**Comment by mkv27** [comment]
Same error with underscores in value:
```sh
$ now dns add test.com test CNAME _a.test.com
> Error! Unexpected error. Please try again later. (Invalid `value` parameter (not a valid FQDN))
```

**Comment by OlliV** [comment]
A valid hostname can't start with `_`.

**Comment by mkv27** [comment]
Right, but some services don't respect this in a validate process for example:
AWS:
http://docs.aws.amazon.com/acm/latest/userguide/images/acm_dns_cname.png

**Comment by OlliV** [comment]
@mkv27 truth, actually I just realized that we use that too. I'll take a look to fix this issue.

**Comment by OlliV** [comment]
@mkv27 it should work now.

**Comment by jjant** [comment]
@OlliV This error still happens on version `11.1.7` of the cli. Should this be reopened?

**Comment by estrattonbailey** [comment]
Seeing in `11.2.9` as well

**Comment by leo** [comment]
We need to fix this. Any help is welcome!

**Comment by Defite** [comment]
It's 2019 and nobody fixed this? Why?

**Comment by TooTallNate** [comment]
I'm going to transfer this issue internally for better visibility and prioritization. Thank you everyone for your patience 🙏
